[workspace]
channels = ["conda-forge"]
name = "legacy-converters"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[tasks]

[dependencies]
xarray = ">=2025.11.0"
numpy = ">=2.3.4,<3"
zarr = ">=3.1.3,<4"
xdggs = ">=0.6.0"
healpix-geo = ">=0.0.11"
dask = ">=2025.2.0"
distributed = ">=2025.2.0"
scipy = ">=1.16.3,<2"
pystac-client = ">=0.9.0,<0.10"
matplotlib = ">=3.10.7,<4"
cartopy = ">=0.25.0,<0.26"
pyproj = ">=3.7.2,<4"
sparse = ">=0.17.0,<0.18"
affine = ">=2.4.0,<3"
opt-einsum = ">=3.4.0,<4"
pytorch = ">=2.9.1,<3"
xbatcher = ">=0.4.0"
numpy_groupies = ">=0.11.3,<0.12"
pydantic = ">=2.12.5,<3"
structlog = ">=25.5.0,<26"

[target.linux-64.dependencies]
pytorch-gpu = ">=2.9.1,<3"


[pypi-dependencies]
legacy-converters = { path = ".", editable = true }
rasterix = ">=0.1"

[feature.dev.dependencies]
jupyterlab = "*"
jupyter-resource-usage = "*"
ruff-lsp = "*"
jedi-language-server = "*"
dask-labextension = "*"
jupyterlab_code_formatter = ">=3.0.2,<4"
black = ">=25.1.0,<26"
isort = ">=7.0.0,<8"
python = "3.13.*"
jupyterlab-nvdashboard = ">=0.13.0,<0.14"
pre-commit = ">=4.5.1,<5"
pip = ">=26.0.1,<27"
ipykernel = ">=7.2.0,<8"
ipython = ">=9.11.0,<10"

[feature.dev.tasks]
jupyterlab = { cmd = "jupyter lab", cwd = "." }

[feature.tests.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.tests.tasks]
tests = { cmd = "pytest --cov=legacy_converters", cwd = "." }

[feature.ci-py313.dependencies]
python = "3.13.*"

[feature.ci-py311.dependencies]
python = "3.11.*"

[feature.profilers.dependencies]
pyinstrument = "*"

[environments]
dev = ["tests", "profilers", "dev"]
ci-py311 = ["tests", "ci-py311"]
ci-py313 = ["tests", "ci-py313"]

[tasks.ci-py311]
depends-on = [{ task = "tests", environment = "ci-py311" }]

[tasks.ci-py313]
depends-on = [{ task = "tests", environment = "ci-py313" }]

[tasks.ci]
depends-on = [{ task = "tests", environment = "dev" }]
